# Generated by Django 4.1.1 on 2022-11-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('other_name', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('d_o_b', models.DateField()),
            ],
        ),
    ]
